[package]
name = "rustyguide"
version = "0.1.0"
authors = ["bakirillov"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

seq_io="*"
regex="*"
lazy_static="*"
serde="*"
serde_json="*"
docopt="*"
indicatif="*"
